/* ============================================
   WORDS THAT HEAL — POEMS DATA
   All poems with translations (EN/ES/ZH/SW)
   ============================================ */

window.LevyPoems = [
  {
    id: 'breathe',
    title: { en: 'Breathe', es: 'Respira', zh: '呼吸', sw: 'Pumzika' },
    date: 'June 2, 2026',
    featured: true,
    free: true,
    lines: {
      en: [
        'Just breathe love, why are you worried?',
        'Why are you stressed?',
        'God has his hand wrapped around you, trust me you\'re blessed.',
        'Just breathe, even when you don\'t see it.',
        'He\'s strengthening you day in and day out, to believe it.',
        'The rage, the anger, the pain.',
        'It all makes you want to break out in flames,',
        'Show out, hate, and point the finger to blame.',
        'Not while he is by your side',
        'To remind you, it\'s ok, stay calm in this rip tide.',
        '',
        'Just breathe love, you\'re doing your absolute best,',
        'Keep showing up, keep pushing forward, your',
        'days are coming where your worries will soon be to rest...'
      ],
      es: [
        'Solo respira amor, ¿por qué estás preocupada?',
        '¿Por qué estás estresada?',
        'Dios tiene su mano envuelta alrededor de ti, créeme estás bendecida.',
        'Solo respira, incluso cuando no lo veas.',
        'Él te está fortaleciendo día tras día, para creerlo.',
        'La rabia, la ira, el dolor.',
        'Todo te hace querer estallar en llamas,',
        'Gritar, odiar, y señalar con el dedo para culpar.',
        'No mientras él está a tu lado',
        'Para recordarte, está bien, mantén la calma en esta marea.',
        '',
        'Solo respira amor, estás dando lo mejor de ti,',
        'Sigue apareciendo, sigue adelante, tus',
        'días llegarán donde tus preocupaciones pronto descansarán...'
      ],
      zh: [
        '只管呼吸吧亲爱的，你为什么担心？',
        '你为什么有压力？',
        '上帝的手环绕着你，相信我，你是被祝福的。',
        '只管呼吸，即使你看不到。',
        '他日日夜夜在坚固你，让你相信。',
        '愤怒、怒火、痛苦。',
        '这一切让你想要爆发，',
        '发泄、仇恨、指责他人。',
        '但他在你身边的时候不会',
        '提醒你，没关系，在这激流中保持平静。',
        '',
        '只管呼吸吧亲爱的，你已经做到最好了，',
        '继续出现，继续前进，你的',
        '日子即将到来，你的忧虑将得到安息...'
      ],
      sw: [
        'Pumzika tu mpenzi, kwa nini una wasiwasi?',
        'Kwa nini una msongo?',
        'Mungu ana mkono wake umekuzunguka, niamini umebarikiwa.',
        'Pumzika tu, hata usipokuona.',
        'Anakuimarisha siku baada ya siku, kuamini.',
        'Ghadhabu, hasira, maumivu.',
        'Yote yanakufanya utake kulipuka kwa moto,',
        'Kupiga kelele, kuchukia, na kumshitaki mtu.',
        'Si wakati yeye yuko kando yako',
        'Kukumbusha, ni sawa, tulia katika mkondo huu.',
        '',
        'Pumzika tu mpenzi, unafanya vizuri kabisa,',
        'Endelea kuonekana, endelea kusonga mbele,',
        'siku zako zinakuja ambapo wasiwasi wako utapumzika...'
      ]
    },
    preview: {
      en: 'Just breathe love, why are you worried? Why are you stressed? God has his hand wrapped around you...',
      es: 'Solo respira amor, ¿por qué estás preocupada? ¿Por qué estás estresada?',
      zh: '只管呼吸吧亲爱的，你为什么担心？你为什么有压力？',
      sw: 'Pumzika tu mpenzi, kwa nini una wasiwasi? Kwa nini una msongo?'
    },
    teaserLines: 5
  },
  {
    id: 'can-i-escape',
    title: { en: 'Can I escape?', es: '¿Puedo escapar?', zh: '我能逃脱吗？', sw: 'Je, naweza kutoroka?' },
    date: 'January 18, 2026',
    featured: false,
    free: false,
    lines: {
      en: [
        'Can I escape from the pain that keeps me from seeing,',
        'Seeing who I truly am, past being a human being.',
        'Loving on me, praising on me, holding myself tight,',
        'Can I escape, from what\'s keeping me from',
        'showing myself, how it\'s done right.',
        'Do I run, do I stay, do I fight, or do I just follow.',
        'To the end of the road, where it\'s nothing but fog',
        '& everything seems hollow.',
        'Can I escape? Will I escape? To a free mind,',
        'open spirit, to see the world in different lenses.',
        'To express that being trapped is a choice, so',
        'consider escaping, listen to that voice.',
        'That challenges me to sit still, and move out of',
        'grace. To help me believe, that I already',
        'escaped, everything takes time, & realizing that',
        'it already happens at its own pace.'
      ],
      es: [
        'Puedo escapar del dolor que me impide ver,',
        'Ver quién realmente soy, más allá de ser un ser humano.',
        'Amándome, alabándome, abrazándome fuerte,',
        'Puedo escapar, de lo que me impide',
        'mostrarme a mí misma, cómo se hace bien.',
        '¿Corro, me quedo, lucho, o simplemente sigo?',
        'Hasta el final del camino, donde no hay más que niebla',
        'y todo parece vacío.',
        '¿Puedo escapar? ¿Escaparé? A una mente libre,',
        'espíritu abierto, para ver el mundo con diferentes lentes.',
        'Para expresar que estar atrapada es una elección, así que',
        'considera escapar, escucha esa voz.',
        'Que me desafía a quedarme quieta, y salir de',
        'la gracia. Para ayudarme a creer, que ya',
        'escapé, todo toma tiempo, y darme cuenta que',
        'ya sucede a su propio ritmo.'
      ],
      zh: [
        '我能逃脱那阻止我看清的痛苦吗，',
        '看清我真正是谁，超越作为一个人的存在。',
        '爱自己，赞美自己，紧紧拥抱自己，',
        '我能逃脱吗，从那阻止我',
        '向自己展示，如何做正确的事。',
        '我该跑吗，该留吗，该战斗吗，还是只是跟随。',
        '走到路的尽头，那里什么都没有只有雾',
        '一切都似乎空洞。',
        '我能逃脱吗？我会逃脱吗？到一个自由的心灵，',
        '开放的灵魂，用不同的镜头看世界。',
        '表达被困住是一种选择，所以',
        '考虑逃脱，听从那个声音。',
        '它挑战我静坐不动，走出',
        '恩典。帮助我相信，我已经',
        '逃脱了，一切都需要时间，并意识到',
        '它已经按自己的节奏发生。'
      ],
      sw: [
        'Je, naweza kutoroka kutoka kwa maumivu yanayonizuia kuona,',
        'Kuona mimi ni nani kweli, zaidi ya kuwa binadamu.',
        'Kunipenda, kunisifu, kujishika sana,',
        'Je, naweza kutoroka, kutoka kwa kinachonizuia',
        'kujionyesha, jinsi inavyofanywa vizuri.',
        'Je, nikimbie, nibaki, nipigane, au nifuate tu.',
        'Hadi mwisho wa barabara, ambapo hakuna chochote ila ukungu',
        'na kila kitu kinaonekana tupu.',
        'Je, naweza kutoroka? Je, nitatokoka? Kwa akili huru,',
        'roho wazi, kuona ulimwengu kwa lenzi tofauti.',
        'Kueleza kwamba kunaswa ni chaguo, kwa hivyo',
        'fikiria kutoroka, sikiliza sauti hiyo.',
        'Inayonishindia kukaa kimya, na kusonga nje ya',
        'neema. Kunisaidia kuamini, kwamba tayari',
        'nimetoroka, kila kitu kinahitaji muda, na kutambua kwamba',
        'tayari kinatokea kwa kasi yake.'
      ]
    },
    preview: {
      en: 'Can I escape from the pain that keeps me from seeing, seeing who I truly am...',
      es: 'Puedo escapar del dolor que me impide ver, ver quién realmente soy...',
      zh: '我能逃脱那阻止我看清的痛苦吗，看清我真正是谁...',
      sw: 'Je, naweza kutoroka kutoka kwa maumivu yanayonizuia kuona...'
    },
    teaserLines: 5
  },
  {
    id: 'how-could-you',
    title: { en: 'How could you?', es: '¿Cómo pudiste?', zh: '你怎么能？', sw: 'Ungewezaje?' },
    date: 'January 15, 2026',
    featured: false,
    free: false,
    lines: {
      en: [
        'How could you leave me in the cold',
        'To fight hard alone and be so bold',
        'How could you watch me suffer, not reach out',
        'Not a call, no hugs, or kisses, definitely made',
        'me have a lot of doubt',
        'How could you see the pain in my eyes, but look away',
        'When I stare deep in your soul searching for an',
        'answer that\'ll never make its way',
        'How could you? Why would you? When I look',
        'just like you, act like you, & smile just like you.',
        'The split image of yourself, a human you',
        'created, some you didn\'t have to do.',
        'How could you allow anyone to break the bond',
        'we shared, the connection I mourn for everyday.',
        'How could you, why would you not allow',
        'genuine love from your own flesh, but accepted',
        'it from a stranger who made this mess anyway.',
        'No blame, no shame, everyone has their own opinion.',
        'But still I ask myself, how could you? I\'m just',
        'praying I seek forgiveness.'
      ],
      es: [
        'Cómo pudiste dejarme en el frío',
        'Para luchar sola con tanta valentía',
        'Cómo pudiste verme sufrir, sin acercarte',
        'Ni una llamada, ni abrazos, ni besos, definitivamente me hiciste',
        'tener muchas dudas',
        'Cómo pudiste ver el dolor en mis ojos, pero mirar hacia otro lado',
        'Cuando miro profundamente en tu alma buscando una',
        'respuesta que nunca llegará',
        'Cómo pudiste? Por qué lo harías? Cuando me veo',
        'igual que tú, actúo como tú, y sonrío igual que tú.',
        'La imagen dividida de ti misma, un humano que',
        'creaste, algo que no tenías que hacer.',
        'Cómo pudiste permitir que alguien rompiera el lazo',
        'que compartíamos, la conexión que lloro cada día.',
        'Cómo pudiste, por qué no permitirías',
        'amor genuino de tu propia sangre, pero aceptaste',
        'el de un extraño que causó este desastre.',
        'Sin culpa, sin vergüenza, cada uno tiene su propia opinión.',
        'Pero aún me pregunto, ¿cómo pudiste? Solo',
        'estoy rezando para buscar el perdón.'
      ],
      zh: [
        '你怎么能把我丢在寒冷中',
        '独自坚强地战斗',
        '你怎么能看着我受苦，却不伸出手',
        '没有电话，没有拥抱，没有亲吻，确实让',
        '我充满了怀疑',
        '你怎么能看到我眼中的痛苦，却转过头去',
        '当我深深凝视你的灵魂，寻找一个',
        '永远不会到来的答案',
        '你怎么能？你为什么要？当我看起来',
        '和你一样，行为像你，笑容像你。',
        '你自己的翻版，一个你',
        '创造的人，有些事你本不必做。',
        '你怎么能允许任何人打破',
        '我们共享的纽带，我每天都在哀悼的联系。',
        '你怎么能，你为什么不允许',
        '来自你亲人的真爱，却接受了',
        '一个制造了这一切混乱的陌生人的。',
        '不怪罪，不羞耻，每个人都有自己的看法。',
        '但我仍然问自己，你怎么能？我只是',
        '在祈祷我能寻得宽恕。'
      ],
      sw: [
        'Ungewezaje kuniacha katika baridi',
        'Kupigana peke yangu kwa ujasiri',
        'Ungewezaje kunitazama nikiteseka, bila kunifikia',
        'Hakuna simu, hakuna kukumbatia, au busu, hakika ulinifanya',
        'kuwa na mashaka mengi',
        'Ungewezaje kuona maumivu machoni pangu, lakini ukatazama mbali',
        'Ninapokutazama ndani ya roho yako nikitafuta',
        'jibu ambalo halitafika kamwe',
        'Ungewezaje? Kwa nini ungefanya hivyo? Wakati ninaonekana',
        'kama wewe, ninatenda kama wewe, na kutabasamu kama wewe.',
        'Picha yako iliyogawanyika, mwanadamu ambaye',
        'ulimuumba, kitu ambacho haukupaswa kufanya.',
        'Ungewezaje kumruhusu mtu yeyote kuvunja kifungo',
        'tulichoshiriki, uhusiano ninaouhuzunikia kila siku.',
        'Ungewezaje, kwa nini usingekubali',
        'upendo wa kweli kutoka kwa nyama yako mwenyewe, lakini ukakubali',
        'kutoka kwa mgeni aliyesababisha fujo hii.',
        'Hakuna lawama, hakuna aibu, kila mtu ana maoni yake.',
        'Lakini bado najiuliza, ungewezaje? Ninaomba tu',
        'nitafute msamaha.'
      ]
    },
    preview: {
      en: 'How could you leave me in the cold, to fight hard alone and be so bold...',
      es: 'Cómo pudiste dejarme en el frío, para luchar sola con tanta valentía...',
      zh: '你怎么能把我丢在寒冷中，独自坚强地战斗...',
      sw: 'Ungewezaje kuniacha katika baridi, kupigana peke yangu kwa ujasiri...'
    },
    teaserLines: 5
  },
  {
    id: 'am-i-the-reason',
    title: { en: 'Am I the reason?', es: '¿Soy yo la razón?', zh: '是我的原因吗？', sw: 'Je, mimi ndio sababu?' },
    date: 'November 19, 2025',
    featured: false,
    free: true,
    lines: {
      en: [
        'Am I the reason it\'s so hard to love me?',
        'Am I the reason I\'m alone and hurting?',
        'Am I the reason for this pain that keeps me suffering?',
        'Am I the reason I\'m sitting here thinking why me?',
        'What can it be?',
        'What is holding me, draining me, and not',
        'allowing me to release.',
        'The joy, the smile, the beauty I hold deep inside of me.',
        '',
        'Sometimes I cry, a lot of times I cry',
        'Praying one day my wings will set free and just fly.',
        '',
        'Far away from misery, from pain',
        'Praying I find a way to gain',
        'Everything I lost, everything I always mourned for',
        '',
        'Nothing you can\'t buy',
        'But something you can always hold close and',
        'it\'ll never die.',
        'I want to be set free from this, and breathe in',
        'calmness and peace',
        'So I can stop asking myself am I the reason no',
        'one loves me.'
      ],
      es: [
        '¿Soy yo la razón por la que es tan difícil amarme?',
        '¿Soy yo la razón por la que estoy sola y sufriendo?',
        '¿Soy yo la razón de este dolor que me hace sufrir?',
        '¿Soy yo la razón por la que estoy aquí pensando por qué yo?',
        '¿Qué puede ser?',
        'Qué me retiene, me drena, y no',
        'me permite liberar.',
        'La alegría, la sonrisa, la belleza que guardo dentro de mí.',
        '',
        'A veces lloro, muchas veces lloro',
        'Rezando que un día mis alas se liberen y simplemente vuelen.',
        '',
        'Lejos de la miseria, del dolor',
        'Rezando para encontrar una manera de recuperar',
        'Todo lo que perdí, todo lo que siempre lloré',
        '',
        'Nada que no puedas comprar',
        'Pero algo que siempre puedes guardar cerca y',
        'nunca morirá.',
        'Quiero ser liberada de esto, y respirar en',
        'calma y paz',
        'Para poder dejar de preguntarme si soy yo la razón por la que',
        'nadie me ama.'
      ],
      zh: [
        '是我的原因吗，为什么爱我这么难？',
        '是我的原因吗，我孤独而痛苦？',
        '是我的原因吗，这痛苦让我不断受苦？',
        '是我的原因吗，我坐在这里想为什么是我？',
        '会是什么？',
        '是什么在束缚我，消耗我，不',
        '让我释放。',
        '那快乐、那微笑、那深藏在我内心的美。',
        '',
        '有时我哭，很多时候我哭',
        '祈祷有一天我的翅膀自由飞翔。',
        '',
        '远离苦难，远离痛苦',
        '祈祷我能找到方法去获得',
        '我失去的一切，我一直哀悼的一切',
        '',
        '那不是金钱能买到的',
        '但你可以永远紧紧握住',
        '它永远不会消亡。',
        '我想从这一切中被释放，呼吸',
        '平静与安宁',
        '这样我就可以停止问自己我是不是',
        '没有人爱我的原因。'
      ],
      sw: [
        'Je, mimi ndio sababu ni vigumu kunipenda?',
        'Je, mimi ndio sababu niko peke yangu na ninahuzunika?',
        'Je, mimi ndio sababu ya maumivu haya yanayonifanya kuteseka?',
        'Je, mimi ndio sababu nimekaa hapa nikifikiri kwa nini mimi?',
        'Kinachoweza kuwa ni nini?',
        'Nini kinachonishika, kuninyonya, na',
        'kunikataza kuachia.',
        'Furaha, tabasamu, uzuri ninaoushika ndani yangu.',
        '',
        'Wakati mwingine nalia, mara nyingi nalia',
        'Nikiomba siku moja mabawa yangu yataachiwa huru na kuruka.',
        '',
        'Mbali na huzuni, na maumivu',
        'Nikiomba nipate njia ya kupata',
        'Kila kitu nilichopoteza, kila kitu nilichoomboleza',
        '',
        'Hakuna chochote usichoweza kununua',
        'Lakini kitu unachoweza kushika karibu daima na',
        'hakitakufa kamwe.',
        'Nataka kuachiliwa huru kutoka kwa hili, na kupumua',
        'utulivu na amani',
        'Ili niweze kuacha kujiuliza je mimi ndio sababu',
        'hakuna anayenipenda.'
      ]
    },
    preview: {
      en: 'Am I the reason it\'s so hard to love me? Am I the reason I\'m alone and hurting?',
      es: '¿Soy yo la razón por la que es tan difícil amarme? ¿Soy yo la razón por la que estoy sola?',
      zh: '是我的原因吗，为什么爱我这么难？是我的原因吗，我孤独而痛苦？',
      sw: 'Je, mimi ndio sababu ni vigumu kunipenda? Je, mimi ndio sababu niko peke yangu?'
    },
    teaserLines: 5
  },
  {
    id: 'the-idea-of-me',
    title: { en: 'The idea of me', es: 'La idea de mí', zh: '我的假象', sw: 'Wazo la mimi' },
    date: 'June 2, 2026',
    featured: false,
    free: false,
    lines: {
      en: [
        'You like me? You love me?',
        'Or I just make things comfortable for where you',
        'wanna be?',
        'Do you think about me in a whole?',
        'Or just enough to know you got my heart stole?',
        'Am I genuinely enough? Am I too easy?',
        'Too easy to love, too easy to hurt, too easy to give.',
        'Too easy to let go, too easy to forgive.',
        'Do you know how I truly feel? Have you figure it out?',
        'Or is it just good to look at me, knowing there',
        'are no doubts.',
        'Do you only see the external me? Is that who you love?',
        'The one who makes everything easier, go',
        'beyond and above.',
        'What about when I can\'t, would you still be around?',
        'To give me the same hope, the same faith, to',
        'keep me from falling to the ground?',
        'Do you see me? Or just the idea of me?',
        'Who you want me to be?',
        'Or the idea of everything coming so easy, so free...'
      ],
      es: [
        '¿Te gusto? ¿Me amas?',
        '¿O solo hago las cosas cómodas para donde',
        'quieres estar?',
        '¿Piensas en mí completamente?',
        '¿O solo lo suficiente para saber que robaste mi corazón?',
        '¿Soy genuinamente suficiente? ¿Soy demasiado fácil?',
        'Demasiado fácil de amar, de herir, de dar.',
        'Demasiado fácil de soltar, demasiado fácil de perdonar.',
        '¿Sabes cómo me siento realmente? ¿Lo has descubierto?',
        '¿O solo es bueno mirarme, sabiendo que no',
        'hay dudas?',
        '¿Solo ves lo externo de mí? ¿Es a quien amas?',
        'La que hace todo más fácil, que va',
        'más allá.',
        '¿Y cuando no pueda, seguirías aquí?',
        'Para darme la misma esperanza, la misma fe, para',
        'evitar que caiga al suelo?',
        '¿Me ves? ¿O solo la idea de mí?',
        '¿Quién quieres que sea?',
        '¿O la idea de que todo viene tan fácil, tan libre...'
      ],
      zh: [
        '你喜欢我？你爱我？',
        '还是我只是让你在想待的地方',
        '更舒适？',
        '你有完整地想过我吗？',
        '还是只够知道你偷走了我的心？',
        '我真的足够吗？我是不是太容易了？',
        '太容易爱，太容易伤害，太容易给予。',
        '太容易放手，太容易原谅。',
        '你知道我真正的感受吗？你弄明白了吗？',
        '还是看着我就好，知道',
        '没有任何疑虑。',
        '你只看到外在的我吗？那是你爱的人吗？',
        '那个让一切变得更容易的人，超越',
        '所有期望。',
        '当我做不到的时候呢，你还会在吗？',
        '给我同样的希望，同样的信念，',
        '让我不会跌落在地？',
        '你看到的是我？还是只是我的假象？',
        '你想让我成为谁？',
        '还是一切来得如此轻松、如此自由的假象...'
      ],
      sw: [
        'Unanipenda? Unanipenda kweli?',
        'Au mimi nafanya mambo kuwa rahisi kwa mahali',
        'unapotaka kuwa?',
        'Unafikiri kunihusu mimi kwa ujumla?',
        'Au tu kutosha kujua umeiiba moyo wangu?',
        'Je, mimi ni wa kutosha kweli? Je, mimi ni rahisi sana?',
        'Rahisi sana kupendwa, kuumizwa, kutoa.',
        'Rahisi sana kuachia, rahisi sana kusamehe.',
        'Je, unajua ninavyohisi kweli? Umegundua?',
        'Au ni vizuri tu kunitazama, ukijua hakuna',
        'mashaka.',
        'Je, unaona tu nje yangu? Ndiye unayempenda?',
        'Yule anayefanya kila kitu kuwa rahisi, kwenda',
        'zaidi na juu.',
        'Je, nisipoweza, bado ungekuwa hapa?',
        'Kunipa tumaini lile lile, imani ile ile, ili',
        'kusinizuia kuanguka chini?',
        'Je, unaniona? Au tu wazo la mimi?',
        'Unataka niwe nani?',
        'Au wazo la kila kitu kinachokuja kwa urahisi, kwa uhuru...'
      ]
    },
    preview: {
      en: 'You like me? You love me? Or I just make things comfortable for where you wanna be?',
      es: '¿Te gusto? ¿Me amas? ¿O solo hago las cosas cómodas para donde quieres estar?',
      zh: '你喜欢我？你爱我？还是我只是让你在想待的地方更舒适？',
      sw: 'Unanipenda? Unanipenda kweli? Au mimi nafanya mambo kuwa rahisi?'
    },
    teaserLines: 5
  }
];

/* ---------- Helper: Get localized text ---------- */
window.LevyPoems.getTitle = function (poem, lang) {
  return (poem.title[lang] || poem.title.en);
};
window.LevyPoems.getLines = function (poem, lang) {
  return (poem.lines[lang] || poem.lines.en);
};
window.LevyPoems.getPreview = function (poem, lang) {
  return (poem.preview[lang] || poem.preview.en);
};
